removing redundant check

diff --git a/orchestrators/azdo/ci_bicep.yml b/orchestrators/azdo/ci_bicep.yml
--- a/orchestrators/azdo/ci_bicep.yml
+++ b/orchestrators/azdo/ci_bicep.yml
@@ -106,21 +106,21 @@ jobs:
             len=${#array[@]}
             for deployment in "${array[@]}"
               do
-                if [[ ${deployment} != *"01_init"* ]]; then
-                  echo "bicep init ${deployment}"
-                  pushd .
-                  cd $deployment
-                  init "true" $deployment $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET)
-                  echo "bicep init ${deployment}"
-                  echo "bicep validate ${deployment}"
-                  validate
-                  code=$?
-                  if [[ $code != 0 ]]; then
+                echo "bicep init ${deployment}"
+                pushd .
+                cd $deployment
+                init "true" $deployment $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET)
+                echo "bicep init ${deployment}"
+                echo "bicep validate ${deployment}"
+                validate
+                code=$?
+                if [[ $code != 0 ]]; then
+                  echo "biceplint failed- returned code ${code}"
                     echo "biceplint failed- returned code ${code}" 
-                    exit $code
-                  fi
-                  popd
-                  echo "------------------------"
+                  echo "biceplint failed- returned code ${code}"
+                  exit $code
                 fi
+                popd
+                echo "------------------------"
               done
             popd
