.

diff --git a/orchestrators/azdo/ci_terraform_validate.yml b/orchestrators/azdo/ci_terraform_validate.yml
--- a/orchestrators/azdo/ci_terraform_validate.yml
+++ b/orchestrators/azdo/ci_terraform_validate.yml
@@ -19,29 +19,42 @@ jobs:
           - checkout: Symphony 
           
           - task: Bash@3
-            displayName: "Install Terraform"
+            displayName: "Setup Toolset"
             inputs:
-              filePath: 'orchestrators/scripts/setup-terraform.sh'
               workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
               arguments:  ${{ parameters.terraformVersion }}
               bashEnvValue: '~/.profile'
               failOnStderr: true
-          
-          - task: Bash@3
-            displayName: "Install Tflint"
-            inputs:
-              filePath: 'orchestrators/scripts/setup-tflint.sh'
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              bashEnvValue: '~/.profile'
-              failOnStderr: true
+              targetType: 'inline'
+                script: |
+                  ./setup-terraform.sh ${{ parameters.terraformVersion }}
+                  ./setup-tflint.sh
+                  ./setup-gitleaks.sh
 
-          - task: Bash@3
-            displayName: "Install gitleaks"
-            inputs:
-              filePath: 'orchestrators/scripts/setup-gitleaks.sh'
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              bashEnvValue: '~/.profile'
-              failOnStderr: true         
+          # - task: Bash@3
+          #   displayName: "Install Terraform"
+          #   inputs:
+          #     filePath: 'orchestrators/scripts/setup-terraform.sh'
+          #     workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+          #     arguments:  ${{ parameters.terraformVersion }}
+          #     bashEnvValue: '~/.profile'
+          #     failOnStderr: true
+          
+          # - task: Bash@3
+          #   displayName: "Install Tflint"
+          #   inputs:
+          #     filePath: 'orchestrators/scripts/setup-tflint.sh'
+          #     workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+          #     bashEnvValue: '~/.profile'
+          #     failOnStderr: true
+
+          # - task: Bash@3
+          #   displayName: "Install gitleaks"
+          #   inputs:
+          #     filePath: 'orchestrators/scripts/setup-gitleaks.sh'
+          #     workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+          #     bashEnvValue: '~/.profile'
+          #     failOnStderr: true         
 
           - task: GoTool@0
             inputs:
@@ -60,7 +73,8 @@ jobs:
                 mkdir results
 
                 source ./scanners.sh
-                run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info' 
+                run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info'
+
           - task: PublishTestResults@2
             displayName: "Publish Gitleaks results"
             inputs:
@@ -72,40 +86,43 @@ jobs:
 
           - task: Bash@3
             displayName: "Run Terraform lint"
+            env:
+              WORKSPACE_PATH: $(System.DefaultWorkingDirectory)
             inputs:
               workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
               targetType: 'inline'
               script: | 
-                echo 'Run tflint'             
-                source ./iac.tf.sh
-                pushd .
+                ./iac.tf.lint.sh
+                # echo 'Run tflint'             
+                # source ./iac.tf.sh
+                # pushd .
 
-                cd ./../../IAC/Terraform/terraform
-                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+                # cd ./../../IAC/Terraform/terraform
+                # modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
                 
-                SAVEIFS=$IFS
-                IFS=$'\n'
+                # SAVEIFS=$IFS
+                # IFS=$'\n'
 
-                array=($modules)
-                IFS=$SAVEIFS
-                len=${#array[@]}
+                # array=($modules)
+                # IFS=$SAVEIFS
+                # len=${#array[@]}
 
-                for deployment in "${array[@]}"
-                  do
-                    echo "linting ${deployment}"
-                    pushd .
-                    cd $deployment
+                # for deployment in "${array[@]}"
+                #   do
+                #     echo "linting ${deployment}"
+                #     pushd .
+                #     cd $deployment
 
-                    lint
-                    code=$?
-                    if [[ $code != 0 ]]; then
-                      echo "tflint failed- returned code ${code}" 
-                      exit $code
-                    fi
-                    popd
-                    echo "------------------------"
-                  done
-                popd
+                #     lint
+                #     code=$?
+                #     if [[ $code != 0 ]]; then
+                #       echo "tflint failed- returned code ${code}" 
+                #       exit $code
+                #     fi
+                #     popd
+                #     echo "------------------------"
+                #   done
+                # popd
 
           - task: AzureKeyVault@2
             displayName: "Pull env cred from Azure Key valut"
