split validate temp

diff --git a/orchestrators/azdo/ci_terraform.yml b/orchestrators/azdo/ci_terraform.yml
--- a/orchestrators/azdo/ci_terraform.yml
+++ b/orchestrators/azdo/ci_terraform.yml
@@ -46,238 +46,239 @@ stages:
  - stage: Validate
    displayName: "Validate Configuration"
    jobs:
-      - job: validate
-        workspace:
-          clean:  resources       
-        displayName: "Validate"
+     - template: ./ci_terraform_validate.yml
+     # - job: validate
+     #   workspace:
+     #     clean:  resources       
+     #   displayName: "Validate"
         #condition: eq('false', 'true')
         #variables:
           #deployments: $[ dependencies.gitDiff.outputs['gitDiff.DEPLOYMENTS'] ]
-        steps:
-          - checkout: Symphony 
+     #   steps:
+     #     - checkout: Symphony 
           
-          - task: Bash@3
-            displayName: "Install Terraform"
-            inputs:
-              filePath: 'orchestrators/scripts/setup-terraform.sh'
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              arguments: "1.1.7"
-              bashEnvValue: '~/.profile'
-              failOnStderr: true
+     #     - task: Bash@3
+     #       displayName: "Install Terraform"
+     #       inputs:
+     #         filePath: 'orchestrators/scripts/setup-terraform.sh'
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         arguments: "1.1.7"
+     #         bashEnvValue: '~/.profile'
+     #         failOnStderr: true
           
-          - task: Bash@3
-            displayName: "Install Tflint"
-            inputs:
-              filePath: 'orchestrators/scripts/setup-tflint.sh'
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              bashEnvValue: '~/.profile'
-              failOnStderr: true
+     #     - task: Bash@3
+     #       displayName: "Install Tflint"
+     #       inputs:
+     #         filePath: 'orchestrators/scripts/setup-tflint.sh'
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         bashEnvValue: '~/.profile'
+     #         failOnStderr: true
 
-          - task: Bash@3
-            displayName: "Install gitleaks"
-            inputs:
-              filePath: 'orchestrators/scripts/setup-gitleaks.sh'
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              bashEnvValue: '~/.profile'
-              failOnStderr: true
+     #     - task: Bash@3
+     #       displayName: "Install gitleaks"
+     #       inputs:
+     #         filePath: 'orchestrators/scripts/setup-gitleaks.sh'
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         bashEnvValue: '~/.profile'
+     #         failOnStderr: true
 
-          #- task: Bash@3
-          #  displayName: "Install Go"
-          #  inputs:
-          #    filePath: 'orchestrators/scripts/setup-go.sh'
-          #    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-          #    arguments: "1.18.1"
-          #    bashEnvValue: '~/.profile'
-          #    failOnStderr: true
+     #     #- task: Bash@3
+     #     #  displayName: "Install Go"
+     #     #  inputs:
+     #     #    filePath: 'orchestrators/scripts/setup-go.sh'
+     #     #    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #     #    arguments: "1.18.1"
+     #     #    bashEnvValue: '~/.profile'
+     #     #    failOnStderr: true
           
-          #- task: Bash@3
-          #  displayName: "Install Go"
-          #  inputs:
-          #    targetType: "inline"
-          #    bashEnvValue: '~/.profile'
-          #    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-          #    script: |
-          #      pushd .
-          #      
-          #      ./setup-go.sh "1.18.1"
-          #      export GOBIN="$(System.DefaultWorkingDirectory)/bin"
+     #     #- task: Bash@3
+     #     #  displayName: "Install Go"
+     #     #  inputs:
+     #     #    targetType: "inline"
+     #     #    bashEnvValue: '~/.profile'
+     #     #    workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #     #    script: |
+     #     #      pushd .
+     #     #      
+     #     #      ./setup-go.sh "1.18.1"
+     #     #      export GOBIN="$(System.DefaultWorkingDirectory)/bin"
 
-          #      echo "--------------------" 
-          #      echo "GOBIN"
-          #      echo $GOBIN  
+     #     #      echo "--------------------" 
+     #     #      echo "GOBIN"
+     #     #      echo $GOBIN  
+     #
+     #     #      popd
+     #   
+     #     #- task: Bash@3
+     #     #  displayName: "echo GOBin, GoPATH, GOROOT"
+     #     #  inputs:
+     #     #    workingDirectory: '$(System.DefaultWorkingDirectory)'
+     #     #    targetType: 'inline'
+     #     #    script: |  
+     #     #      echo "--------------------" 
+     #     #      echo "GOBIN"
+     #     #      echo $GOBIN  
+     #     #      echo "--------------------" 
+     #     #      echo "GOPATH"
+     #     #      echo $GOPATH  
+     #     #       echo "--------------------" 
+     #     #      echo "GOBROOT"
+     #     #      echo $GOROOT  
 
-          #      popd
-        
-          #- task: Bash@3
-          #  displayName: "echo GOBin, GoPATH, GOROOT"
-          #  inputs:
-          #    workingDirectory: '$(System.DefaultWorkingDirectory)'
-          #    targetType: 'inline'
-          #    script: |  
-          #      echo "--------------------" 
-          #      echo "GOBIN"
-          #      echo $GOBIN  
-          #      echo "--------------------" 
-          #      echo "GOPATH"
-          #      echo $GOPATH  
-          #       echo "--------------------" 
-          #      echo "GOBROOT"
-          #      echo $GOROOT  
+     #     - task: GoTool@0
+     #       inputs:
+     #         version: '1.18.1'
+     #         goBin: "$(System.DefaultWorkingDirectory)"
 
-          - task: GoTool@0
-            inputs:
-              version: '1.18.1'
-              goBin: "$(System.DefaultWorkingDirectory)"
-
-          - script: echo '##vso[task.prependpath]$(System.DefaultWorkingDirectory)'
+     #     - script: echo '##vso[task.prependpath]$(System.DefaultWorkingDirectory)'
           
-          - task: Bash@3
-            displayName: "Run gitleaks"
-            inputs:
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              targetType: 'inline'
-              script: | 
-                echo 'create ./results directory'
-                mkdir results
+     #     - task: Bash@3
+     #       displayName: "Run gitleaks"
+     #       inputs:
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         targetType: 'inline'
+     #         script: | 
+     #           echo 'create ./results directory'
+     #           mkdir results
 
-                source ./scanners.sh
-                run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info' 
-          - task: PublishTestResults@2
-            displayName: "Publish Gitleaks results"
-            inputs:
-              testResultsFiles: "*.json"
-              searchFolder: "$(System.DefaultWorkingDirectory)/IAC/Terraform/results"
-              failTaskOnFailedTests: true
-              testRunTitle: "Gitleask report"
-              mergeTestResults: true
+     #           source ./scanners.sh
+     #           run_gitleaks './../../IAC/Terraform' './results/gitleaks-report' 'json' 'info' 
+     #     - task: PublishTestResults@2
+     #       displayName: "Publish Gitleaks results"
+     #       inputs:
+     #         testResultsFiles: "*.json"
+     #         searchFolder: "$(System.DefaultWorkingDirectory)/IAC/Terraform/results"
+     #         failTaskOnFailedTests: true
+     #         testRunTitle: "Gitleask report"
+     #         mergeTestResults: true
 
-          - task: Bash@3
-            displayName: "Run Terraform lint"
-            inputs:
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              targetType: 'inline'
-              script: | 
-                echo 'Run tflint'             
-                source ./iac.tf.sh
-                pushd .
+     #     - task: Bash@3
+     #       displayName: "Run Terraform lint"
+     #       inputs:
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         targetType: 'inline'
+     #         script: | 
+     #           echo 'Run tflint'             
+     #           source ./iac.tf.sh
+     #           pushd .
 
-                cd ./../../IAC/Terraform/terraform
-                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+     #           cd ./../../IAC/Terraform/terraform
+     #           modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
                 
-                SAVEIFS=$IFS
-                IFS=$'\n'
+     #           SAVEIFS=$IFS
+     #           IFS=$'\n'
 
-                array=($modules)
-                IFS=$SAVEIFS
-                len=${#array[@]}
+     #           array=($modules)
+     #           IFS=$SAVEIFS
+     #           len=${#array[@]}
 
-                for deployment in "${array[@]}"
-                  do
-                    echo "linting ${deployment}"
-                    pushd .
-                    cd $deployment
+     #           for deployment in "${array[@]}"
+     #             do
+     #               echo "linting ${deployment}"
+     #               pushd .
+     #               cd $deployment
 
-                    lint
-                    code=$?
-                    if [[ $code != 0 ]]; then
-                      echo "tflint failed- returned code ${code}" 
-                      exit $code
-                    fi
-                    popd
-                    echo "------------------------"
-                  done
-                popd
+     #               lint
+     #               code=$?
+     #               if [[ $code != 0 ]]; then
+     #                echo "tflint failed- returned code ${code}" 
+     #                 exit $code
+     #               fi
+     #               popd
+     #               echo "------------------------"
+     #             done
+     #           popd
 
-          - task: AzureKeyVault@2
-            displayName: "Pull env cred from Azure Key valut"
-            inputs:
-              azureSubscription: 'Symphony-kv2' #'Symphony-kv'#$(SUBID)
-              KeyVaultName: 'kv-symphony-env'
-              SecretsFilter: '*'
-              RunAsPreJob: true
+     #     - task: AzureKeyVault@2
+     #       displayName: "Pull env cred from Azure Key valut"
+     #       inputs:
+     #         azureSubscription: 'Symphony-kv2' #'Symphony-kv'#$(SUBID)
+     #         KeyVaultName: 'kv-symphony-env'
+     #         SecretsFilter: '*'
+     #         RunAsPreJob: true
 
-          - task: Bash@3
-            displayName: "Run Terraform validate"
-            inputs:
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              targetType: 'inline'
-              script: |         
-                source ./iac.tf.sh
-                pushd .
+     #     - task: Bash@3
+     #       displayName: "Run Terraform validate"
+     #       inputs:
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         targetType: 'inline'
+     #         script: |         
+     #           source ./iac.tf.sh
+     #           pushd .
 
-                cd ./../../IAC/Terraform/terraform
-                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+     #           cd ./../../IAC/Terraform/terraform
+     #           modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+     #           
+     #           SAVEIFS=$IFS
+     #           IFS=$'\n'
+
+     #           array=($modules)
+     #           IFS=$SAVEIFS
+     #           len=${#array[@]}
+
+     #           echo "Az login"
+
+     #           azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
+     #           for deployment in "${array[@]}"
+     #             do
+     #               if [[ ${deployment} != *"01_init"* ]]; then
+     #                 echo "tf init ${deployment}"
+     #                 pushd .
+     #                 cd $deployment
+
+     #                 init true "$(ENV)${deployment}.tfstate" $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) $(STATESTORAGEACCOUNT) $(STATECONTAINER) $(STATERG)
+     #                 echo "tf init ${deployment}"
+     #                 echo "tf validate ${deployment}"
+     #                 validate
+     #                 code=$?
+     #                 if [[ $code != 0 ]]; then
+     #                   echo "terraform validate - returned code ${code}" 
+     #                   exit $code
+     #                 fi
+     #                 popd
+     #                 echo "------------------------"
+     #               fi
+     #             done
+     #           popd
+
+     #     - task: Bash@3
+     #       displayName: "Run Modules tests"
+     #       inputs:
+     #         workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+     #         targetType: 'inline'
+     #         script: |         
+     #           source ./tests.runner.sh
+     #           azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
                 
-                SAVEIFS=$IFS
-                IFS=$'\n'
+     #           #install junit 
+     #           echo "install go-junit-report"
+     #           go install github.com/jstemmer/go-junit-report@latest
 
-                array=($modules)
-                IFS=$SAVEIFS
-                len=${#array[@]}
+     #           # set test vars
+     #           export resource_group_name=$(STATERG)
+     #           export storage_account_name=$(STATESTORAGEACCOUNT) 
+     #           export container_name=$(STATECONTAINER)
 
-                echo "Az login"
-
-                azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
-                for deployment in "${array[@]}"
-                  do
-                    if [[ ${deployment} != *"01_init"* ]]; then
-                      echo "tf init ${deployment}"
-                      pushd .
-                      cd $deployment
-
-                      init true "$(ENV)${deployment}.tfstate" $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) $(STATESTORAGEACCOUNT) $(STATECONTAINER) $(STATERG)
-                      echo "tf init ${deployment}"
-                      echo "tf validate ${deployment}"
-                      validate
-                      code=$?
-                      if [[ $code != 0 ]]; then
-                        echo "terraform validate - returned code ${code}" 
-                        exit $code
-                      fi
-                      popd
-                      echo "------------------------"
-                    fi
-                  done
-                popd
-
-          - task: Bash@3
-            displayName: "Run Modules tests"
-            inputs:
-              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
-              targetType: 'inline'
-              script: |         
-                source ./tests.runner.sh
-                azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
+     #           pushd .
                 
-                #install junit 
-                echo "install go-junit-report"
-                go install github.com/jstemmer/go-junit-report@latest
-
-                # set test vars
-                export resource_group_name=$(STATERG)
-                export storage_account_name=$(STATESTORAGEACCOUNT) 
-                export container_name=$(STATECONTAINER)
-
-                pushd .
-                
-                cd ./../../IAC/Terraform/test/terraform
+     #           cd ./../../IAC/Terraform/test/terraform
           
 
-                echo "Run tests with tag = module_tests"
-                terraform module_test true
+     #           echo "Run tests with tag = module_tests"
+     #           terraform module_test true
               
-                popd
+     #           popd
 
-          - task: PublishTestResults@2
-            displayName: "Publish modules unit test results"
-            inputs:
-              testResultsFormat: "JUnit"
-              testResultsFiles: "*.xml"
-              searchFolder: "$(System.DefaultWorkingDirectory)/IAC/Terraform/test/terraform"
-              failTaskOnFailedTests: true
-              testRunTitle: "Terraform Modules unit tests"
-              publishRunAttachments: true
-              mergeTestResults: true
+     #     - task: PublishTestResults@2
+     #       displayName: "Publish modules unit test results"
+     #       inputs:
+     #         testResultsFormat: "JUnit"
+     #         testResultsFiles: "*.xml"
+     #         searchFolder: "$(System.DefaultWorkingDirectory)/IAC/Terraform/test/terraform"
+     #         failTaskOnFailedTests: true
+     #         testRunTitle: "Terraform Modules unit tests"
+     #         publishRunAttachments: true
+     #         mergeTestResults: true
 
 
       - job: preview
