Update ci_terraform.yml for Azure Pipelines

diff --git a/orchestrators/azdo/ci_terraform.yml b/orchestrators/azdo/ci_terraform.yml
--- a/orchestrators/azdo/ci_terraform.yml
+++ b/orchestrators/azdo/ci_terraform.yml
@@ -188,25 +188,25 @@ stages:
 
                 azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
                 for deployment in "${array[@]}"
-                        do
-                          if [[ ${deployment} != *"01_init"* ]]; then
-                            echo "tf init ${deployment}"
-                            pushd .
-                            cd $deployment
+                  do
+                    if [[ ${deployment} != *"01_init"* ]]; then
+                      echo "tf init ${deployment}"
+                      pushd .
+                      cd $deployment
 
-                            init true "${deployment}" $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) $(STATESTORAGEACCOUNT) $(STATECONTAINER) $(STATERG)
-                            echo "tf init ${deployment}"
-                            echo "tf validate ${deployment}"
-                            validate
-                            code=$?
-                            if [[ $code != 0 ]]; then
-                              echo "tflint failed- returned code ${code}" 
-                              exit $code
-                            fi
-                            popd
-                            echo "------------------------"
-                          fi
-                        done
+                      init true "${deployment}" $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) $(STATESTORAGEACCOUNT) $(STATECONTAINER) $(STATERG)
+                      echo "tf init ${deployment}"
+                      echo "tf validate ${deployment}"
+                      validate
+                      code=$?
+                      if [[ $code != 0 ]]; then
+                        echo "tflint failed- returned code ${code}" 
+                        exit $code
+                      fi
+                      popd
+                      echo "------------------------"
+                    fi
+                  done
                 popd
 
           - task: Bash@3
@@ -219,7 +219,7 @@ stages:
                 azlogin "" "" "" "" "" 
                 pushd .
 
-                cd ./../../IAC/Terraform/terraform
+                cd ./../../IAC/Terraform/test
                 modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
                 
                 SAVEIFS=$IFS
