Update ci_terraform.yml for Azure Pipelines

diff --git a/orchestrators/azdo/ci_terraform.yml b/orchestrators/azdo/ci_terraform.yml
--- a/orchestrators/azdo/ci_terraform.yml
+++ b/orchestrators/azdo/ci_terraform.yml
@@ -136,12 +136,48 @@ stages:
                             echo "tflint failed- returned code ${code}" 
                             exit $code
                           fi
-                          echo "tflint succeeded" 
                           popd
                           echo "------------------------"
                         done
                 popd
 
+          - task: Bash@3
+            displayName: "Run Terraform validate"
+            inputs:
+              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+              targetType: 'inline'
+              script: | 
+                echo 'Run tflint'             
+                source ./iac.tf.sh
+                pushd .
+
+                cd ./../../IAC/Terraform/terraform
+                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+                
+                SAVEIFS=$IFS
+                IFS=$'\n'
+
+                array=($modules)
+                IFS=$SAVEIFS
+                len=${#array[@]}
+
+                for deployment in "${array[@]}"
+                        do
+                          echo "linting ${deployment}"
+                          pushd .
+                          cd $deployment
+
+                          init
+                          validate
+                          code=$?
+                          if [[ $code != 0 ]]; then
+                            echo "tflint failed- returned code ${code}" 
+                            exit $code
+                          fi
+                          popd
+                          echo "------------------------"
+                        done
+                popd
   
           
 
