Update ci_terraform.yml for Azure Pipelines

diff --git a/orchestrators/azdo/ci_terraform.yml b/orchestrators/azdo/ci_terraform.yml
--- a/orchestrators/azdo/ci_terraform.yml
+++ b/orchestrators/azdo/ci_terraform.yml
@@ -172,7 +172,6 @@ stages:
               targetType: 'inline'
               script: |         
                 source ./iac.tf.sh
-                azlogin "" "" "" "" "" 
                 pushd .
 
                 cd ./../../IAC/Terraform/terraform
@@ -210,7 +209,50 @@ stages:
                         done
                 popd
 
-          
+          - task: Bash@3
+            displayName: "Run Module test"
+            inputs:
+              workingDirectory: '$(System.DefaultWorkingDirectory)/orchestrators/scripts'
+              targetType: 'inline'
+              script: |         
+                source ./iac.tf.sh
+                azlogin "" "" "" "" "" 
+                pushd .
+
+                cd ./../../IAC/Terraform/terraform
+                modules=$(find . -type d | sort | awk '$0 !~ last "/" {print last} {last=$0} END {print last}')
+                
+                SAVEIFS=$IFS
+                IFS=$'\n'
+
+                array=($modules)
+                IFS=$SAVEIFS
+                len=${#array[@]}
+
+                echo "Az login"
+
+                azlogin $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) 'AzureCloud'
+                for deployment in "${array[@]}"
+                        do
+                          if [[ ${deployment} != *"01_init"* ]]; then
+                            echo "tf init ${deployment}"
+                            pushd .
+                            cd $deployment
+
+                            init true "${deployment}" $(SUBID) $(TENANTID) $(CLIENTID) $(CLIENTSECRET) $(STATESTORAGEACCOUNT) $(STATECONTAINER) $(STATERG)
+                            echo "tf init ${deployment}"
+                            echo "tf validate ${deployment}"
+                            validate
+                            code=$?
+                            if [[ $code != 0 ]]; then
+                              echo "tflint failed- returned code ${code}" 
+                              exit $code
+                            fi
+                            popd
+                            echo "------------------------"
+                          fi
+                        done
+                popd
 
                 
                  
