.

diff --git a/.github/workflows/workflow.main.bicep.yml b/.github/workflows/workflow.main.bicep.yml
--- a/.github/workflows/workflow.main.bicep.yml
+++ b/.github/workflows/workflow.main.bicep.yml
@@ -12,6 +12,10 @@ on:
         description: 'Environment'     
         required: true
         default: 'dev'
+      location:
+        description: 'Location'     
+        required: true
+        default: 'westus'
 
 jobs:
   Validate:
@@ -96,12 +100,12 @@ jobs:
               extraFileParam="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/${path//.\//}/parameters.json"
               echo "${extraFileParam}"
               if [[ -f "${extraFileParam}" ]]; then
-                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json @${extraFileParam}"
+                  paramFiles="@${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json @${extraFileParam}"
               else
-                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json"
+                  paramFiles="@${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json"
               fi
 
-              validate "${fileName}" "${paramFiles}" "${{ github.run_id }}" "westus"
+              validate "${fileName}" "${paramFiles}" "${{ github.run_id }}" "${{ github.event.inputs.location }}"
               code=$?
               if [[ $code != 0 ]]; then
                 echo "biceplint failed- returned code ${code}"
@@ -123,11 +127,58 @@ jobs:
     needs: Validate
     runs-on: ubuntu-latest
     steps:
-      # - uses: actions/checkout@v3
+      - uses: actions/checkout@v3
 
-      - name: Run script
+      - uses: Azure/login@v1
+        with:
+          creds: "${{ secrets.AZURE_CREDENTIALS }}"
+
+      - uses: Azure/get-keyvault-secrets@v1
+        with:
+          keyvault: "kv-symphony-env"
+          secrets: "clientid, clientsecret, subid, tenantid"
+        id: KvSecrets
+
+      - name: Run Bicep Validate
         run: |
-          echo Hello world!
+          source ./iac.bicep.sh
+          azlogin ${{ steps.KvSecrets.outputs.subid }} ${{ steps.KvSecrets.outputs.tenantid }} ${{ steps.KvSecrets.outputs.clientid }} ${{ steps.KvSecrets.outputs.clientsecret }} 'AzureCloud'
+          pushd .
+          cd ./../../IAC/Bicep/bicep
+          modules=$(find . -type f -name 'main.bicep' | sort -u)
+
+          SAVEIFS=$IFS
+          IFS=$'\n'
+          array=(${modules})
+          IFS=$SAVEIFS
+          len=${#array[@]}
+          for deployment in "${array[@]}"
+            do
+              pushd .
+              path=$(dirname "${deployment}")
+              fileName=$(basename "${deployment}")
+              cd "${path}"
+              echo "bicep validating ${path}/${fileName}"
+
+              extraFileParam="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/${path//.\//}/parameters.json"
+              echo "${extraFileParam}"
+              if [[ -f "${extraFileParam}" ]]; then
+                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json @${extraFileParam}"
+              else
+                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json"
+              fi
+
+              validate "${fileName}" "${paramFiles}" "${{ github.run_id }}" "${{ github.event.inputs.location }}"
+              code=$?
+              if [[ $code != 0 ]]; then
+                echo "biceplint failed- returned code ${code}"
+                exit $code
+              fi
+              popd
+              echo "------------------------"
+            done
+          popd
+        working-directory: orchestrators/scripts
 
   Deploy:
     name: "Deploy"
