add test template

diff --git a/.github/workflows/workflow.main.tf.yml b/.github/workflows/workflow.main.tf.yml
--- a/.github/workflows/workflow.main.tf.yml
+++ b/.github/workflows/workflow.main.tf.yml
@@ -44,9 +44,17 @@ jobs:
         terraformVersion: ${{ github.event.inputs.terraformVersion }}
     secrets:
         azEnvCred: ${{ secrets.AZURE_CREDENTIALS }}
-    # name: "Preview and Deploy"    
-    # needs: Validate
-    
+
+  Test:
+    uses: ./.github/workflows/tf_test.yml
+    needs: PreviewDeploy
+    with:
+        environment: ${{ github.event.inputs.environment }}
+        terraformVersion: ${{ github.event.inputs.terraformVersion }}
+        goVersion: ${{ github.event.inputs.goVersion }}
+        runLayerTest: false
+    secrets:
+        azEnvCred: ${{ secrets.AZURE_CREDENTIALS }}
     # runs-on: ubuntu-latest
     # steps:
     #   - uses: actions/checkout@v3
@@ -54,7 +62,7 @@ jobs:
     #   - name: Setup Toolset
     #     run: |
     #       ./setup-azcli.sh
-    #       chmod +x  ./setup-terraform.sh
+    #       chmod +x  ./setup-terraform.sh 
     #       ./setup-terraform.sh ${{ github.event.inputs.terraformVersion }}
     #     working-directory: orchestrators/scripts
     #     shell: bash       
@@ -71,7 +79,10 @@ jobs:
     #       secrets: "clientid, clientsecret, subid, tenantid, staterg, statecontainer, statestorageaccount"
     #     id: KvSecrets
 
-    #   - name: Run TF plan- Apply
+    #   - uses: actions/setup-go@v3
+    #     with:
+    #       go-version: ${{ github.event.inputs.goVersion }}
+    #   - name: Run Modules Tests
     #     env:
     #       SUBID: ${{ steps.KvSecrets.outputs.subid }}
     #       TENANTID: ${{ steps.KvSecrets.outputs.tenantid }}
@@ -81,87 +92,39 @@ jobs:
     #       STATECONTAINER: ${{ steps.KvSecrets.outputs.statecontainer }}
     #       STATERG: ${{ steps.KvSecrets.outputs.staterg }}
     #       ENV: ${{ github.event.inputs.environment }}
-    #       WORKSPACE_PATH: ${{ github.workspace }}
     #     run: |
-    #       chmod +x . ./iac.tf.previewdeploy.sh
-    #       ./iac.tf.previewdeploy.sh
+    #       source ./tests.runner.sh
+    #       azlogin "${SUBID}" "${TENANTID}" "$CLIENTID" "$CLIENTSECRET" 'AzureCloud'
           
+    #       #install junit 
+    #       echo "install go-junit-report"
+    #       go install github.com/jstemmer/go-junit-report@latest
+
+    #       # set test vars
+    #       export resource_group_name="${STATERG}"
+    #       export storage_account_name="${STATESTORAGEACCOUNT}"
+    #       export container_name="${STATECONTAINER}"
+
+    #       pushd ./../../IAC/Terraform/test/terraform
+    #       echo "Run tests with tag = e2e_test"
+    #       terraform e2e_test true        
+    #       popd
+
     #     working-directory: orchestrators/scripts
     #     shell: bash
 
-  Test:
-    name: "Test"
-    needs: PreviewDeploy
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
-
-      - name: Setup Toolset
-        run: |
-          ./setup-azcli.sh
-          chmod +x  ./setup-terraform.sh 
-          ./setup-terraform.sh ${{ github.event.inputs.terraformVersion }}
-        working-directory: orchestrators/scripts
-        shell: bash       
-
-      - uses: Azure/login@v1
-        name: Run Azure Login
-        with:
-          creds: "${{ secrets.AZURE_CREDENTIALS }}"
-
-      - uses: Azure/get-keyvault-secrets@v1
-        name: Get KeyVault Secrets
-        with:
-          keyvault: "kv-symphony-env"
-          secrets: "clientid, clientsecret, subid, tenantid, staterg, statecontainer, statestorageaccount"
-        id: KvSecrets
-
-      - uses: actions/setup-go@v3
-        with:
-          go-version: ${{ github.event.inputs.goVersion }}
-      - name: Run Modules Tests
-        env:
-          SUBID: ${{ steps.KvSecrets.outputs.subid }}
-          TENANTID: ${{ steps.KvSecrets.outputs.tenantid }}
-          CLIENTID: ${{ steps.KvSecrets.outputs.clientid }}
-          CLIENTSECRET: ${{ steps.KvSecrets.outputs.clientsecret }}
-          STATESTORAGEACCOUNT: ${{ steps.KvSecrets.outputs.statestorageaccount }}
-          STATECONTAINER: ${{ steps.KvSecrets.outputs.statecontainer }}
-          STATERG: ${{ steps.KvSecrets.outputs.staterg }}
-          ENV: ${{ github.event.inputs.environment }}
-        run: |
-          source ./tests.runner.sh
-          azlogin "${SUBID}" "${TENANTID}" "$CLIENTID" "$CLIENTSECRET" 'AzureCloud'
-          
-          #install junit 
-          echo "install go-junit-report"
-          go install github.com/jstemmer/go-junit-report@latest
-
-          # set test vars
-          export resource_group_name="${STATERG}"
-          export storage_account_name="${STATESTORAGEACCOUNT}"
-          export container_name="${STATECONTAINER}"
-
-          pushd ./../../IAC/Terraform/test/terraform
-          echo "Run tests with tag = e2e_test"
-          terraform e2e_test true        
-          popd
-
-        working-directory: orchestrators/scripts
-        shell: bash
-
-      - uses: actions/upload-artifact@v2  
-        if: success() || failure()
-        with:
-          name: End to End Test results
-          path: ./IAC/Terraform/test/terraform/*.xml
+    #   - uses: actions/upload-artifact@v2  
+    #     if: success() || failure()
+    #     with:
+    #       name: End to End Test results
+    #       path: ./IAC/Terraform/test/terraform/*.xml
       
-      - name: Publish End to End Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v1
-        if: always()
-        with:
-          files: "./IAC/Terraform/test/terraform/*.xml"
-          check_name: "End2End tests Results"
+    #   - name: Publish End to End Test Results
+    #     uses: EnricoMi/publish-unit-test-result-action@v1
+    #     if: always()
+    #     with:
+    #       files: "./IAC/Terraform/test/terraform/*.xml"
+    #       check_name: "End2End tests Results"
 
   Report:
     name: "Report"
