.

diff --git a/.github/workflows/workflow.main.bicep.yml b/.github/workflows/workflow.main.bicep.yml
--- a/.github/workflows/workflow.main.bicep.yml
+++ b/.github/workflows/workflow.main.bicep.yml
@@ -9,13 +9,13 @@ on:
   workflow_dispatch:
     inputs:
       environment:
-        description: 'Environment'     
+        description: "Environment"
         required: true
-        default: 'dev'
+        default: "dev"
       location:
-        description: 'Location'     
+        description: "Location"
         required: true
-        default: 'westus'
+        default: "westus"
 
 jobs:
   Validate:
@@ -36,41 +36,43 @@ jobs:
 
       - name: Run Gitleaks
         run: |
-            source ./scanners.sh
-            run_gitleaks './../../IAC/Bicep' './' 'json' 'info'
+          source ./scanners.sh
+          run_gitleaks './../../IAC/Bicep' './' 'json' 'info'
         working-directory: orchestrators/scripts
 
       - name: Run Bicep Lint
         run: |
-            source ./iac.bicep.sh
-            pushd .
-            cd ./../../IAC/Bicep/bicep
-            modules=$(find . -type f -name '*.bicep' | sort -u)
+          source ./iac.bicep.sh
+          pushd .
+          cd ./../../IAC/Bicep/bicep
+          modules=$(find . -type f -name '*.bicep' | sort -u)
 
-            SAVEIFS=$IFS
-            IFS=$'\n'
-            array=($modules)
-            IFS=$SAVEIFS
-            len=${#array[@]}
-            for deployment in "${array[@]}"
-              do
-                echo "linting ${deployment}"
-                lint "${deployment}"
-                code=$?
-                if [[ $code != 0 ]]; then
-                  echo "bicep linting failed - returned code ${code}"
-                  exit $code
-                fi
-                echo "------------------------"
-              done
-            popd
+          SAVEIFS=$IFS
+          IFS=$'\n'
+          array=($modules)
+          IFS=$SAVEIFS
+          len=${#array[@]}
+          for deployment in "${array[@]}"
+            do
+              echo "linting ${deployment}"
+              lint "${deployment}"
+              code=$?
+              if [[ $code != 0 ]]; then
+                echo "bicep linting failed - returned code ${code}"
+                exit $code
+              fi
+              echo "------------------------"
+            done
+          popd
         working-directory: orchestrators/scripts
 
       - uses: Azure/login@v1
+        name: Run Azure Login
         with:
           creds: "${{ secrets.AZURE_CREDENTIALS }}"
 
       - uses: Azure/get-keyvault-secrets@v1
+        name: Get KeyVault Secrets
         with:
           keyvault: "kv-symphony-env"
           secrets: "clientid, clientsecret, subid, tenantid"
@@ -123,92 +125,92 @@ jobs:
   #   with:
   #     environment: "dev"
 
-  Preview:
-    name: "Preview"
-    needs: Validate
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v3
+  # Preview:
+  #   name: "Preview"
+  #   needs: Validate
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v3
 
-      - uses: Azure/login@v1
-        with:
-          creds: "${{ secrets.AZURE_CREDENTIALS }}"
+  #     - uses: Azure/login@v1
+  #       with:
+  #         creds: "${{ secrets.AZURE_CREDENTIALS }}"
 
-      - uses: Azure/get-keyvault-secrets@v1
-        with:
-          keyvault: "kv-symphony-env"
-          secrets: "clientid, clientsecret, subid, tenantid"
-        id: KvSecrets
+  #     - uses: Azure/get-keyvault-secrets@v1
+  #       with:
+  #         keyvault: "kv-symphony-env"
+  #         secrets: "clientid, clientsecret, subid, tenantid"
+  #       id: KvSecrets
 
-      - name: Run Bicep Preview
-        run: |
-          source ./iac.bicep.sh
-          azlogin ${{ steps.KvSecrets.outputs.subid }} ${{ steps.KvSecrets.outputs.tenantid }} ${{ steps.KvSecrets.outputs.clientid }} ${{ steps.KvSecrets.outputs.clientsecret }} 'AzureCloud'
-          pushd .
-          cd ./../../IAC/Bicep/bicep
-          modules=$(find . -type f -name 'main.bicep' | sort -u)
+  #     - name: Run Bicep Preview
+  #       run: |
+  #         source ./iac.bicep.sh
+  #         azlogin ${{ steps.KvSecrets.outputs.subid }} ${{ steps.KvSecrets.outputs.tenantid }} ${{ steps.KvSecrets.outputs.clientid }} ${{ steps.KvSecrets.outputs.clientsecret }} 'AzureCloud'
+  #         pushd .
+  #         cd ./../../IAC/Bicep/bicep
+  #         modules=$(find . -type f -name 'main.bicep' | sort -u)
 
-          SAVEIFS=$IFS
-          IFS=$'\n'
-          array=(${modules})
-          IFS=$SAVEIFS
-          len=${#array[@]}
-          for deployment in "${array[@]}"
-            do
-              pushd .
-              path=$(dirname "${deployment}")
-              fileName=$(basename "${deployment}")
-              cd "${path}"
-              echo "bicep preview ${path}/${fileName}"
+  #         SAVEIFS=$IFS
+  #         IFS=$'\n'
+  #         array=(${modules})
+  #         IFS=$SAVEIFS
+  #         len=${#array[@]}
+  #         for deployment in "${array[@]}"
+  #           do
+  #             pushd .
+  #             path=$(dirname "${deployment}")
+  #             fileName=$(basename "${deployment}")
+  #             cd "${path}"
+  #             echo "bicep preview ${path}/${fileName}"
 
-              extraFileParam="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/${path//.\//}/parameters.json"
-              if [[ -f "${extraFileParam}" ]]; then
-                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json @${extraFileParam}"
-              else
-                  paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json"
-              fi
+  #             extraFileParam="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/${path//.\//}/parameters.json"
+  #             if [[ -f "${extraFileParam}" ]]; then
+  #                 paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json @${extraFileParam}"
+  #             else
+  #                 paramFiles="${{ github.workspace }}/env/bicep/${{ github.event.inputs.environment }}/parameters.json"
+  #             fi
 
-              preview "${fileName}" "${paramFiles}" "${{ github.run_id }}" "${{ github.event.inputs.location }}"
-              code=$?
-              if [[ $code != 0 ]]; then
-                echo "biceplint failed - returned code ${code}"
-                exit $code
-              fi
-              popd
-              echo "------------------------"
-            done
-          popd
-        working-directory: orchestrators/scripts
+  #             preview "${fileName}" "${paramFiles}" "${{ github.run_id }}" "${{ github.event.inputs.location }}"
+  #             code=$?
+  #             if [[ $code != 0 ]]; then
+  #               echo "biceplint failed - returned code ${code}"
+  #               exit $code
+  #             fi
+  #             popd
+  #             echo "------------------------"
+  #           done
+  #         popd
+  #       working-directory: orchestrators/scripts
 
-  Deploy:
-    name: "Deploy"
-    needs: Preview
-    runs-on: ubuntu-latest
-    steps:
-      # - uses: actions/checkout@v3
+  # Deploy:
+  #   name: "Deploy"
+  #   needs: Preview
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # - uses: actions/checkout@v3
 
-      - name: Run script
-        run: |
-          echo Hello world!
+  #     - name: Run script
+  #       run: |
+  #         echo Hello world!
 
-  Test:
-    name: "Test"
-    needs: Deploy
-    runs-on: ubuntu-latest
-    steps:
-      # - uses: actions/checkout@v3
+  # Test:
+  #   name: "Test"
+  #   needs: Deploy
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # - uses: actions/checkout@v3
 
-      - name: Run script
-        run: |
-          echo Hello world!
+  #     - name: Run script
+  #       run: |
+  #         echo Hello world!
 
-  Report:
-    name: "Report"
-    needs: Test
-    runs-on: ubuntu-latest
-    steps:
-      # - uses: actions/checkout@v3
+  # Report:
+  #   name: "Report"
+  #   needs: Test
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     # - uses: actions/checkout@v3
 
-      - name: Run script
-        run: |
-          echo Hello world!
+  #     - name: Run script
+  #       run: |
+  #         echo Hello world!
